services:
  app:
    build: ./
    container_name: liquide-test
    ports:
      - "3000:3000"
    env_file: .env.test # Load environment variables
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    container_name: liquide-postgres-test
    restart: always
    env_file: .env.test # Load environment variables
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-test:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: liquide-redis-test
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data-test:/data

volumes:
  postgres-data-test:
  redis-data-test:
